'use strict';
// Starter catalogue for the "125+ Ways to Participate" page.
// STATUSES ARE PLACEHOLDERS: management must confirm each one in Admin → Pathways
// before launch. Only pathways this platform actually supports today are
// marked "available"; everything else is coming_soon / in_development / partner.

const A = 'available';
const S = 'coming_soon';
const D = 'in_development';
const P = 'partner';

module.exports = [
  {
    slug: 'food-ai-data',
    name: 'Food & AI Data',
    tagline: 'Help teach AI what great food looks like.',
    image: '/img/food/salad-bowl.webp',
    icon: 'database',
    items: [
      ['Snap & Tag Dishes', 'Photograph meals and tag the dish to help train Chew food recognition.', D],
      ['Recipe Verification', 'Review AI-generated recipes for accuracy and flag anything that looks wrong.', D],
      ['Ingredient Labeling', 'Label ingredients in food images for the Chew dataset.', D],
      ['Regional Cuisine Collection', 'Contribute dishes and recipes from your region or culture.', S],
      ['Menu Digitization', 'Help turn printed restaurant menus into structured data.', S],
      ['Nutrition Data Review', 'Check nutrition estimates against package labels.', D],
      ['Taste & Rating Feedback', 'Rate recipes you cook to improve recommendations.', S],
      ['Cooking Technique Clips', 'Record short technique clips for the video dataset.', D],
      ['Grocery Price Reporting', 'Report local ingredient prices to power smarter shopping lists.', S],
      ['Dietary Tagging', 'Tag dishes as vegan, gluten-free, halal, kosher and more.', D],
      ['Food Translation', 'Translate dish names and ingredients into other languages.', S],
      ['Allergen Review', 'Help identify common allergens in recipes.', D],
      ['Home Cook Survey Panels', 'Share how you shop, cook and eat in short research panels.', S],
      ['Pantry Scan Contributions', 'Share pantry photos to improve ingredient detection.', D],
      ['AI Image Quality Review', 'Review AI food images and flag low-quality results.', D],
      ['Data Ambassador', 'Recruit and support food-data contributors in your community.', S],
    ],
  },
  {
    slug: 'social-media-content',
    name: 'Social Media & Content',
    tagline: 'Serve ready-made content from the Content Kitchen.',
    image: '/img/food/flatlay.webp',
    icon: 'share',
    items: [
      ['Share Content Kitchen Posts', 'Post ready-made Content Kitchen videos and images with your tracked link.', A],
      ['Short-Form Video Creator', 'Create Reels, TikToks and Shorts that feature Chew.', S],
      ['Recipe Remix Challenges', 'Join community challenges that put a twist on a Chew recipe.', S],
      ['Food Photography Contributor', 'Submit original food photography for Chew channels.', S],
      ['Live Cooking Host', 'Host live cooking sessions using See It. Cook It.', D],
      ['Community Group Moderator', 'Help run Chew community groups.', S],
      ['Blog & Newsletter Writer', 'Write recipes and food stories for your own audience.', S],
      ['Pinterest Recipe Boards', 'Curate Chew recipe boards on Pinterest.', S],
      ['YouTube Channel Partner', 'Partner with Chew on long-form cooking video.', P],
      ['Podcast Mentions', 'Talk about Chew on food and technology podcasts.', S],
      ['Reviews & Testimonials', 'Share your honest experience with Chew products.', D],
      ['Hashtag Campaigns', 'Take part in seasonal Chew hashtag campaigns.', S],
      ['Seasonal & Holiday Content', 'Share holiday recipes and seasonal food content.', S],
      ['Micro-Influencer Program', 'A dedicated program for creators with engaged audiences.', P],
      ['Content Localization', 'Adapt Chew content for your language and market.', S],
      ['Content Kitchen Contributor', 'Pitch and produce content for the Content Kitchen.', D],
    ],
  },
  {
    slug: 'ai-technology',
    name: 'AI Technology',
    tagline: 'Put Chew’s food AI in more hands.',
    image: '/img/food/eggs-spinach.webp',
    icon: 'cpu',
    items: [
      ['Share See It. Cook It.', 'Share the See It. Cook It. app with your tracked download link.', A],
      ['Beta Tester Program', 'Try new AI features before they launch.', D],
      ['AI Recipe Generator Feedback', 'Test the recipe generator and send structured feedback.', D],
      ['Voice Cooking Assistant Testing', 'Help test hands-free voice guidance in the kitchen.', D],
      ['Smart Meal Planner', 'Share Chew’s AI weekly meal planner.', S],
      ['AI Grocery List Referrals', 'Share AI-built grocery lists that link to partner stores.', S],
      ['Chew API Developer Program', 'For developers building on Chew food AI.', P],
      ['Smart Kitchen Integrations', 'Refer smart-appliance makers to Chew integrations.', P],
      ['AI Video Recipe Showcase', 'Share AI-generated “see it cook” recipe videos.', D],
      ['AI Agent Referrals', 'Referrals that begin in a conversation with a Chew AI assistant.', D],
      ['Feature Request Program', 'Suggest features and get recognized when they ship.', S],
      ['Bug Reporting Program', 'Report reproducible bugs in Chew apps.', S],
      ['AI Nutrition Coach Pilot', 'Join the pilot for AI nutrition coaching.', D],
      ['Accessibility Testing', 'Help make Chew apps work for everyone.', S],
      ['Enterprise AI Referrals', 'Introduce businesses to Chew food AI licensing.', P],
      ['App Localization Testing', 'Test Chew apps in your language.', S],
    ],
  },
  {
    slug: 'chef-pepe',
    name: 'Chef Pepe',
    tagline: 'Bring Chef Pepe into more kitchens.',
    image: '/img/food/kitchen-friends.webp',
    icon: 'chef',
    items: [
      ['Chef Pepe Recipe Shares', 'Share Chef Pepe recipes with your audience.', S],
      ['Chef Pepe Kids Cooking Series', 'Family-friendly cooking lessons with Chef Pepe.', D],
      ['Chef Pepe Character Content', 'Share approved Chef Pepe character posts and clips.', S],
      ['Chef Pepe Merchandise', 'Refer customers to official Chef Pepe merchandise.', S],
      ['Chef Pepe Live Events', 'Help promote Chef Pepe appearances and events.', S],
      ['Chef Pepe Stickers & GIFs', 'Share Chef Pepe stickers and GIFs in chats.', D],
      ['Chef Pepe Cookbook', 'Share the Chef Pepe cookbook.', S],
      ['Chef Pepe School Programs', 'Introduce Chef Pepe lessons to schools.', D],
      ['Chef Pepe Voice Assistant', 'Share Chef Pepe as a voice cooking companion.', D],
      ['Chef Pepe Challenges', 'Join cooking challenges hosted by Chef Pepe.', S],
      ['Chef Pepe Licensing', 'Introduce brands interested in licensing Chef Pepe.', P],
      ['Chef Pepe Fan Community', 'Help grow the Chef Pepe fan community.', S],
      ['Chef Pepe Animated Shorts', 'Share Chef Pepe animated shorts.', D],
      ['Chef Pepe Holiday Specials', 'Share seasonal Chef Pepe specials.', S],
      ['Chef Pepe Brand Collaborations', 'Co-branded Chef Pepe campaigns with partners.', P],
      ['Chef Pepe Ambassador', 'Represent Chef Pepe in your community.', S],
    ],
  },
  {
    slug: 'products-commerce',
    name: 'Products & Commerce',
    tagline: 'Connect people with food products they’ll love.',
    image: '/img/food/grill-platter.webp',
    icon: 'store',
    items: [
      ['Chew Marketplace Referrals', 'Refer shoppers to the Chew marketplace.', S],
      ['Kitchen Tools & Gear', 'Refer customers to partner kitchen tools.', P],
      ['Meal Kit Referrals', 'Refer customers to partner meal kits.', P],
      ['Grocery Delivery Referrals', 'Refer customers to partner grocery delivery.', P],
      ['Specialty Ingredients', 'Share hard-to-find ingredients from Chew suppliers.', S],
      ['Chew Branded Products', 'Share official Chew products.', S],
      ['Digital Recipe Packs', 'Share premium digital recipe collections.', D],
      ['Premium Subscription Referrals', 'Refer members to a premium Chew subscription.', D],
      ['Gift Cards', 'Share Chew gift cards.', S],
      ['Cookware Bundles', 'Refer customers to partner cookware bundles.', P],
      ['Healthy Snacks Line', 'Share a Chew healthy snacks line.', S],
      ['Spice & Sauce Collection', 'Share a Chew spice and sauce collection.', S],
      ['Kitchen Appliance Partners', 'Refer customers to partner appliances.', P],
      ['Corporate Gifting', 'Introduce companies to Chew food gifting.', S],
      ['Affiliate Storefront', 'Your own curated Chew storefront page.', D],
      ['Seasonal Product Drops', 'Share limited seasonal product drops.', S],
    ],
  },
  {
    slug: 'restaurants-local',
    name: 'Restaurants & Local',
    tagline: 'Bring your neighborhood’s food onto Chew.',
    image: '/img/food/restaurant.webp',
    icon: 'utensils',
    items: [
      ['Restaurant Onboarding Referrals', 'Introduce local restaurants to Chew.', D],
      ['Local Menu Listings', 'Help local spots get their menus listed.', S],
      ['Food Truck Network', 'Bring food trucks into the Chew network.', S],
      ['Farmers Market Partners', 'Connect farmers markets with Chew shoppers.', S],
      ['Local Chef Spotlights', 'Nominate and feature local chefs.', S],
      ['Restaurant Photos & Reviews', 'Share honest dish photos and reviews.', S],
      ['Catering Referrals', 'Refer catering customers to partner caterers.', P],
      ['Cooking Class Hosts', 'Host local cooking classes that use Chew.', S],
      ['Pop-Up Dinner Events', 'Help run Chew pop-up dinners.', S],
      ['Local Grocery Partners', 'Introduce independent grocers to Chew.', P],
      ['Restaurant AI Tools', 'Introduce restaurants to Chew AI menu tools.', D],
      ['Neighborhood Food Guides', 'Create guides to the best food near you.', S],
      ['Ghost Kitchen Partners', 'Refer delivery-only kitchens to Chew.', P],
      ['Local Business Ambassador', 'Be Chew’s point of contact for local businesses.', S],
      ['Campus Dining Programs', 'Bring Chew to campus dining.', S],
      ['Community Food Drives', 'Organize food drives with the Chew community.', S],
    ],
  },
  {
    slug: 'media-brand',
    name: 'Media & Brand',
    tagline: 'Help tell the Chew story.',
    image: '/img/food/pizza.webp',
    icon: 'film',
    items: [
      ['Brand Ambassador Program', 'Represent Chew at events and online.', S],
      ['Chew Short-Film Features', 'Appear in or help produce Chew short films.', D],
      ['Sponsored Content Partnerships', 'Paid content partnerships run with Chew partners.', P],
      ['Press & Media Introductions', 'Introduce journalists and media to Chew.', S],
      ['Event Appearances', 'Represent Chew at food and tech events.', S],
      ['Brand Sponsorship Introductions', 'Introduce brands interested in sponsoring Chew.', P],
      ['Chew Streaming Channel', 'Share Chew’s streaming food channel.', D],
      ['Documentary Participation', 'Take part in Chew documentary projects.', S],
      ['Product Demo Videos', 'Share official Chew product demos.', D],
      ['Photo & Video Licensing', 'License your food media to Chew.', S],
      ['Co-Branded Campaigns', 'Campaigns with Chew and a partner brand.', P],
      ['Advertising Introductions', 'Introduce advertisers to Chew media.', P],
      ['Speaking & Workshops', 'Speak about Chew at workshops and meetups.', S],
      ['Awards & Competitions', 'Enter Chew food and content competitions.', S],
      ['Brand Asset Localization', 'Adapt Chew brand assets for your market.', S],
      ['Merch Design Contests', 'Design Chew merchandise.', S],
    ],
  },
  {
    slug: 'network-expansion',
    name: 'Network Expansion',
    tagline: 'Grow the Chew community.',
    image: '/img/food/table-spread.webp',
    icon: 'network',
    items: [
      ['Refer New Affiliates', 'Invite people to join the free affiliate program with your link or QR code.', A],
      ['Team Leader Program', 'Support and train affiliates you’ve referred.', S],
      ['International Market Launches', 'Help launch Chew in new countries.', D],
      ['Community Ambassador', 'Represent Chew in your local community.', S],
      ['Campus Ambassador', 'Represent Chew at your college or university.', S],
      ['Affiliate Mentor', 'Mentor new affiliates through their first month.', S],
      ['Language Community Leader', 'Lead a Chew community in your language.', S],
      ['Webinar Host', 'Host Chew introduction webinars.', S],
      ['Local Meetup Organizer', 'Organize local Chew meetups.', S],
      ['Partner Organization Referrals', 'Introduce organizations to Chew partnerships.', P],
      ['Nonprofit & Charity Partnerships', 'Connect nonprofits with Chew food programs.', P],
      ['AI-Agent Referral Handoffs', 'Warm handoffs from Chew AI assistants to affiliates.', D],
      ['Success Manager Program', 'Work with Chew success managers to onboard new affiliates.', S],
      ['Corporate Wellness Programs', 'Introduce employers to Chew wellness programs.', P],
      ['Creator Recruitment', 'Invite food creators to join Chew.', S],
      ['Country Launch Teams', 'Join the team that opens a new country.', D],
    ],
  },
];
